Repository Dungeon-CampusMinden/dojo-dungeon, pull requests merged in 2024-04, with the labels that each got.

#50 Implementation for room 10
  dojo-dungeon/src/level/rooms/Room.java
  dojo-dungeon/src/level/rooms/Room10.java
Labels: enhancement

#53 Prevent inventory from opening over other HUD items
  dungeon/src/contrib/entities/HeroFactory.java
  dungeon/src/contrib/hud/UIUtils.java
  game/src/core/components/PlayerComponent.java
Labels: bug

#55 Add more complex regexes to room 3
  dojo-dungeon/src/level/rooms/Room3.java
Labels: enhancement

#52 Implementation for room 12
  dojo-dungeon/src/level/monster/MyImp.java
  dojo-dungeon/src/level/rooms/Room12.java
Labels: enhancement

#51 Implementation for room 11
  dojo-dungeon/src/level/rooms/Room11.java
Labels: enhancement

#65 Update of the Game Concept
  dojo-dungeon/doc/dojo_dungeon_concept.md
Labels: documentation
